apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        revision: master
        directories:
          - path: '*'
  template:
    metadata:
      name: 'dev'
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        targetRevision: master
        path: '*'
        directory:
          jsonnet: {}
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: testns1
      syncPolicy:
        automated:
          prune: false
          allowEmpty: false
          selfHeal: false
